[workspace]
resolver = "3"
members = [
    "crates/fermata",
    "crates/design",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/oxur/fermata"
rust-version = "1.85"
